### ISSUE TITLE
Fix Group Inventory Items by Product Catalog, Purchase Date, and Expiration Date

### ISSUE THREAD

**Issue by Norbbs** [fjborquez/azula#48]
**As a** Data Owner
**I want to** group the inventory items with the same product catalog, purchase date, expiration date
**So that** I can maintain a single consolidated item for products with the same attributes, allowing for more accurate inventory management and reducing redundancy

### Definition Of Ready (DoR)
|   | **Definition**                                   |  **Observations**  |
|---|----------------------------------------------|---|
|  <ul><li>- [ ] </li></ul> | Story affected                                            |  **ZUKO** **#4** |
|  <ul><li>- [ ] </li></ul> | Environment                                                    |  **prod** |
|  <ul><li>- [ ] </li></ul> | Severity                                                     | **High**  |

### Bug Description
Currently, the inventory system does not consolidate items with the same product catalog, purchase date, and expiration date, leading to potential overcounting and difficulty in inventory tracking.

### ADDITIONAL INFORMATION
Story **ZUKO** **#4**

### Steps to Reproduce
1. Access the inventory management module.
2. Add an item of 900 grams of chicken with a specific product catalog, purchase date, and expiration date.
3. Add another item of 2 kg of chicken with the same product catalog, purchase date, and expiration date.
4. Observe the inventory list.

### Expected Behavior
Items that share the same product catalog, purchase date, and expiration date should be grouped together, showing a total weight (2.9 kg in this case) instead of separate entries.

### Actual Behavior
Inventory shows two separate entries for the same product, leading to confusion and inaccuracies in stock levels.

### Impact

1. Grouping items improves clarity in inventory tracking and management, allowing for easier assessments of stock levels.
2. It reduces clutter in the inventory list, providing a cleaner and more organized view for users.
3. Accurate grouping can prevent stock discrepancies, aiding in better decision-making for restocking and purchasing.
4. This change enhances user experience, as it streamlines operations and reduces the time spent managing inventory.

**Comment by fjborquez** [comment]
Usaste azula o katara-back para agregar los productos?

**Comment by Norbbs** [comment]
@fjborquez  No recuerdo si fue azula o katara-back donde hiciste la agregación de producto

**Comment by fjborquez** [comment]
@Norbbs puedes probar usando katara-back?

**Comment by Norbbs** [comment]
Como lo pruebo?

**Comment by Norbbs** [comment]
@fjborquez estoy probando pero me da error 500

![Image](https://github.com/user-attachments/assets/4771e12d-898f-4ab9-87e1-5603cdc42ac9)

**Comment by fjborquez** [comment]
El purchase_date está mal. No existe el 31 de Noviembre. Cambia esa fecha por una que exista y funcionará.

**Comment by Norbbs** [comment]
@fjborquez  LOL! es verdad, dale funcionó, muevo la tarjeta pero igual crearé otro ticket para después creo que hay que se deberían aplicar unos triggers para que esto no pase en base de datos
